[package]
name = "compressed-intvec"
version = "0.5.2"
edition = "2021"
authors = ["Luca Lombardo"]
description = "Space-efficient integer vectors for Rust. Offers a fixed-width implementation for O(1) mutable and atomic access, and a variable-width implementation that uses instantaneous codes and sampling for high compression ratios on non-uniform data."
readme = "README.md"
license = "Apache-2.0"
repository = "https://github.com/lukefleed/compressed-intvec"
keywords = ["compression", "vector", "integer", "data-structures", "succinct"]
categories = ["data-structures", "compression", "algorithms"]
exclude = [".github/*", "images/*", "python/*"]

[dependencies]
atomic = "0.5.3"
bytemuck = { version = "1.23.1", optional = true }
common_traits = "0.12.0"
dsi-bitstream = { version = "0.5.0", features = ["mem_dbg"] }
mem_dbg = "0.3.0"
num-traits = "0.2.19"
parking_lot = "0.12.4"
rayon = { version = "1.10.0", optional = true }
serde = { version = "1.0.219", features = ["derive"], optional = true }


[dev-dependencies]
simple-sds-sbwt = "0.3.2"
bincode = "1.3.3"
criterion = { version = "0.5.1", features = ["html_reports"] }
rand_distr = "0.5.0"
csv = "1.3.1"
serde_json = "1.0.141"
sux = "0.8.0"
succinct = "0.5.2"
rand = "0.9.0"

# --- Benchmark Targets ---

[[bench]]
name = "bench_random_access"
harness = false
path = "benches/fixed/bench_random_access.rs"

[[bench]]
name = "bench_access_patterns"
harness = false
path = "benches/fixed/bench_access_patterns.rs"

[[bench]]
name = "bench_sequential_ops"
harness = false
path = "benches/fixed/bench_sequential_ops.rs"

[[bench]]
name = "bench_mutable_ops"
harness = false
path = "benches/fixed/bench_mutable_ops.rs"

[[bench]]
name = "bench_atomic"
harness = false
path = "benches/fixed/bench_atomic.rs"

[[bench]]
name = "bench_iter_access"
harness = false
path = "benches/variable/bench_iter_access.rs"

[[bench]]
name = "bench_var_sequential_ops"
harness = false
path = "benches/variable/bench_sequential_ops.rs"

[[bench]]
name = "bench_construction"
harness = false
path = "benches/variable/bench_construction.rs"

[[bench]]
name = "bench_var_random_access"
harness = false
path = "benches/variable/bench_random_access.rs"

[[bench]]
name = "bench_var_parallel"
harness = false
path = "benches/variable/bench_parallel.rs"

[[bench]]
name = "bench_size"
harness = false
path = "benches/bench_size.rs"

[[bench]]
name = "benchmark_lock_free_access"
harness = false
path = "benches/fixed/benchmark_lock_free_access.rs"

[[bench]]
name = "benchmark_locked_access"
harness = false
path = "benches/fixed/benchmark_locked_access.rs"

[[bench]]
name = "bench_random_write"
harness = false
path = "benches/fixed/bench_random_write.rs"

[[bench]]
name = "bench_seq_access_patterns"
harness = false
path = "benches/seq/bench_seq_access_patterns.rs"

[[bench]]
name = "bench_seq_readers"
harness = false
path = "benches/seq/bench_seq_readers.rs"

[[bench]]
name = "bench_seq_streaming"
harness = false
path = "benches/seq/bench_seq_streaming.rs"

[features]
default = ["parallel"]
parallel = ["rayon"]
serde = ["dep:serde"]
arch-dependent-storable = []


# --- Build Profiles ---

[profile.release]
# Standard release optimizations.
opt-level = 3
# Include debug information in release builds.
# The impact on runtime performance is negligible, but the binary size increases.
debug = true
overflow-checks = false

[profile.bench]
# Aggressive optimizations for benchmarks, at the cost of
# much longer compile times
opt-level = 3
# Enable "fat" Link-Time Optimization to allow optimizations across the entire crate.
lto = "fat"
# Disable debug info for benchmark binaries to get the cleanest performance measurement.
debug = false
# Force the compiler to process the crate as a single unit, enabling more
# aggressive inlining and optimization.
codegen-units = 1
