[package]
name = "compressed-intvec"
version = "0.4.0"
edition = "2021"
authors = ["Luca Lombardo"]
description = "A compressed integer vector with fast random access that stores values with instantaneous codes in a bitstream"
readme = "README.md"
license = "Apache-2.0"
repository = "https://github.com/lukefleed/compressed-intvec"
keywords = [
    "compression",
    "vector",
    "bitstream",
    "data-compression",
    "integer-encoding",
]
categories = ["data-structures", "compression", "algorithms"]
exclude = [".github/*", "images/*"]

[dependencies]
atomic = "0.5.3"
bytemuck = { version = "1.23.1", optional = true }
common_traits = "0.12.0"
dsi-bitstream = {version = "0.5.0", features = ["mem_dbg"]}
mem_dbg = "0.3.0"
num-traits = "0.2.19"
parking_lot = "0.12.4"
rayon = { version = "1.10.0", optional = true }
serde = { version = "1.0.219", features = ["derive"], optional = true }
rand = "0.9.0"


[dev-dependencies]
bincode = "1.3.3"
criterion = { version = "0.5.1", features = ["html_reports"] }
rand_distr = "0.5.0"
csv = "1.3.1"
serde_json = "1.0.141"
sux = "0.8.0"

[[bench]]
name = "bench_random_access"
harness = false
path = "benches/fixed/bench_random_access.rs"

[[bench]]
name = "bench_access_patterns"
harness = false
path = "benches/fixed/bench_access_patterns.rs"

[[bench]]
name = "bench_sequential_ops"
harness = false
path = "benches/fixed/bench_sequential_ops.rs"

[[bench]]
name = "bench_mutable_ops"
harness = false
path = "benches/fixed/bench_mutable_ops.rs"

[[bench]]
name = "bench_atomic"
harness = false
path = "benches/fixed/bench_atomic.rs"

[[bench]]
name = "bench_iter_access"
harness = false
path = "benches/variable/bench_iter_access.rs"

[[bench]]
name = "bench_var_sequential_ops"
harness = false
path = "benches/variable/bench_sequential_ops.rs"

[[bench]]
name = "bench_construction"
harness = false
path = "benches/variable/bench_construction.rs"

[[bench]]
name = "bench_var_random_access"
harness = false
path = "benches/variable/bench_random_access.rs"

[[bench]]
name = "bench_var_parallel"
harness = false
path = "benches/variable/bench_parallel.rs"


[features]
default = ["parallel"]
parallel = ["rayon"]
serde = ["dep:serde"]
